@echo off
mkdir MTDebug
mkdir Debug
mkdir MTRelease
mkdir Release

echo ------ MTDebug Win32 ------
cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/rfc_message.obj" /Fd"MTDebug/" /W3 /c /ZI "..\mimetic\rfc822\message.cxx"
cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/rfc_header.obj" /Fd"MTDebug/" /W3 /c /ZI "..\mimetic\rfc822\header.cxx"
cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/os_utils.obj" /Fd"MTDebug/" /W3 /c /ZI "..\mimetic\os\utils.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\codec\qp.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\codec\base64.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\messageid.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\mailboxlist.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\mailbox.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\group.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\fieldvalue.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\field.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\datetime.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\addresslist.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\rfc822\address.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\os\stdfile.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\os\fileop.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\os\file_iterator.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\version.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\utils.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\strutils.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\mimeversion.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\mimeentity.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\message.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\header.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\fieldparam.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\contenttype.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\contenttransferencoding.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\contentid.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\contentdisposition.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\contentdescription.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MTd /Fp".\MTDebug/libmimetic.pch" /Fo".\MTDebug/" /Fd".\MTDebug/" /W3 /c /ZI ..\mimetic\body.cxx"

lib /nologo "/OUT:.\libmimetic_mtd.lib" ".\mtdebug\body.obj" ".\mtdebug\contentdescription.obj" ".\mtdebug\contentdisposition.obj" ".\mtdebug\contentid.obj" ".\mtdebug\contenttransferencoding.obj" ".\mtdebug\contenttype.obj" ".\mtdebug\fieldparam.obj" ".\mtdebug\header.obj" ".\mtdebug\message.obj" ".\mtdebug\mimeentity.obj" ".\mtdebug\mimeversion.obj" ".\mtdebug\strutils.obj" ".\mtdebug\utils.obj" ".\mtdebug\version.obj" ".\mtdebug\file_iterator.obj" ".\mtdebug\fileop.obj" ".\mtdebug\stdfile.obj" ".\mtdebug\address.obj" ".\mtdebug\addresslist.obj" ".\mtdebug\datetime.obj" ".\mtdebug\field.obj" ".\mtdebug\fieldvalue.obj" ".\mtdebug\group.obj" ".\mtdebug\mailbox.obj" ".\mtdebug\mailboxlist.obj" ".\mtdebug\messageid.obj" ".\mtdebug\base64.obj" ".\mtdebug\qp.obj" ".\mtdebug\os_utils.obj" ".\mtdebug\rfc_header.obj" ".\mtdebug\rfc_message.obj" 

echo ------ MTRelease Win32 ------

cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/rfc_message.obj" /Fd".\MTRelease/" /W3 /c /TP "..\mimetic\rfc822\message.cxx"
cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/rfc_header.obj" /Fd".\MTRelease/" /W3 /c /TP "..\mimetic\rfc822\header.cxx"
cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/os_utils.obj" /Fd".\MTRelease/" /W3 /c /TP "..\mimetic\os\utils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\codec\qp.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\codec\base64.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\messageid.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\mailboxlist.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\mailbox.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\group.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\fieldvalue.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\field.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\datetime.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\addresslist.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\rfc822\address.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\os\stdfile.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\os\fileop.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\os\file_iterator.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\version.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\utils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\strutils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\mimeversion.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\mimeentity.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\message.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\header.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\fieldparam.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\contenttype.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\contenttransferencoding.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\contentid.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\contentdisposition.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\contentdescription.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /MT /Fp".\MTRelease/libmimetic.pch" /Fo".\MTRelease/" /Fd".\MTRelease/" /W3 /c /TP ..\mimetic\body.cxx"
lib /nologo "/OUT:.\libmimetic_mt.lib" ".\mtrelease\body.obj" ".\mtrelease\contentdescription.obj" ".\mtrelease\contentdisposition.obj" ".\mtrelease\contentid.obj" ".\mtrelease\contenttransferencoding.obj" ".\mtrelease\contenttype.obj" ".\mtrelease\fieldparam.obj" ".\mtrelease\header.obj" ".\mtrelease\message.obj" ".\mtrelease\mimeentity.obj" ".\mtrelease\mimeversion.obj" ".\mtrelease\strutils.obj" ".\mtrelease\utils.obj" ".\mtrelease\version.obj" ".\mtrelease\file_iterator.obj" ".\mtrelease\fileop.obj" ".\mtrelease\stdfile.obj" ".\mtrelease\address.obj" ".\mtrelease\addresslist.obj" ".\mtrelease\datetime.obj" ".\mtrelease\field.obj" ".\mtrelease\fieldvalue.obj" ".\mtrelease\group.obj" ".\mtrelease\mailbox.obj" ".\mtrelease\mailboxlist.obj" ".\mtrelease\messageid.obj" ".\mtrelease\base64.obj" ".\mtrelease\qp.obj" ".\mtrelease\os_utils.obj" ".\mtrelease\rfc_header.obj" ".\mtrelease\rfc_message.obj" 

echo ----- Release Win32 ------

cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/rfc_message.obj" /Fd".\Release/" /W3 /c /TP "..\mimetic\rfc822\message.cxx"
cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/rfc_header.obj" /Fd".\Release/" /W3 /c /TP "..\mimetic\rfc822\header.cxx"
cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/os_utils.obj" /Fd".\Release/" /W3 /c /TP "..\mimetic\os\utils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\codec\qp.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\codec\base64.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\messageid.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\mailboxlist.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\mailbox.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\group.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\fieldvalue.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\field.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\datetime.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\addresslist.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\rfc822\address.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\os\stdfile.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\os\fileop.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\os\file_iterator.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\version.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\utils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\strutils.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\mimeversion.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\mimeentity.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\message.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\header.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\fieldparam.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\contenttype.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\contenttransferencoding.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\contentid.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\contentdisposition.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\contentdescription.cxx"
 cl /O2 /nologo /I ".." /D "WIN32" /D "NDEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /ML /Fp".\Release/libmimetic.pch" /Fo".\Release/" /Fd".\Release/" /W3 /c /TP ..\mimetic\body.cxx"
lib /nologo "/OUT:.\.\libmimetic.lib" ".\release\body.obj" ".\release\contentdescription.obj" ".\release\contentdisposition.obj" ".\release\contentid.obj" ".\release\contenttransferencoding.obj" ".\release\contenttype.obj" ".\release\fieldparam.obj" ".\release\header.obj" ".\release\message.obj" ".\release\mimeentity.obj" ".\release\mimeversion.obj" ".\release\strutils.obj" ".\release\utils.obj" ".\release\version.obj" ".\release\file_iterator.obj" ".\release\fileop.obj" ".\release\stdfile.obj" ".\release\address.obj" ".\release\addresslist.obj" ".\release\datetime.obj" ".\release\field.obj" ".\release\fieldvalue.obj" ".\release\group.obj" ".\release\mailbox.obj" ".\release\mailboxlist.obj" ".\release\messageid.obj" ".\release\base64.obj" ".\release\qp.obj" ".\release\os_utils.obj" ".\release\rfc_header.obj" ".\release\rfc_message.obj" 

echo ------ Debug Win32 ------

 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\codec\qp.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\codec\base64.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\messageid.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\mailboxlist.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\mailbox.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\group.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\fieldvalue.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\field.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\datetime.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\addresslist.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\rfc822\address.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\os\stdfile.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\os\fileop.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\os\file_iterator.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\version.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\utils.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\strutils.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\mimeversion.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\mimeentity.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\message.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\header.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\fieldparam.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\contenttype.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\contenttransferencoding.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\contentid.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\contentdisposition.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\contentdescription.cxx"
 cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/" /Fd".\Debug/" /W3 /c /ZI ..\mimetic\body.cxx"

cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/rfc_message.obj" /Fd"Debug/" /W3 /c /ZI "..\mimetic\rfc822\message.cxx"
cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/rfc_header.obj" /Fd"Debug/" /W3 /c /ZI "..\mimetic\rfc822\header.cxx"
cl /Od /nologo /I ".." /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_MBCS" /FD /EHsc /RTC1 /MLd /Fp".\Debug/libmimetic.pch" /Fo".\Debug/os_utils.obj" /Fd"Debug/" /W3 /c /ZI "..\mimetic\os\utils.cxx"


lib /nologo "/OUT:.\libmimetic_d.lib" ".\debug\body.obj" ".\debug\contentdescription.obj" ".\debug\contentdisposition.obj" ".\debug\contentid.obj" ".\debug\contenttransferencoding.obj" ".\debug\contenttype.obj" ".\debug\fieldparam.obj" ".\debug\header.obj" ".\debug\message.obj" ".\debug\mimeentity.obj" ".\debug\mimeversion.obj" ".\debug\strutils.obj" ".\debug\utils.obj" ".\debug\version.obj" ".\debug\file_iterator.obj" ".\debug\fileop.obj" ".\debug\stdfile.obj" ".\debug\address.obj" ".\debug\addresslist.obj" ".\debug\datetime.obj" ".\debug\field.obj" ".\debug\fieldvalue.obj" ".\debug\group.obj" ".\debug\mailbox.obj" ".\debug\mailboxlist.obj" ".\debug\messageid.obj" ".\debug\base64.obj" ".\debug\qp.obj" ".\debug\os_utils.obj" ".\debug\rfc_header.obj" ".\debug\rfc_message.obj" 
